version: '3'
services:
  mysql:
    container_name: mysql
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: crm
      MYSQL_USER: mysqluser
      MYSQL_PASSWORD: mysqlpassword
      MYSQL_ROOT_PASSWORD: mysqlrootpassword
    healthcheck:
      test: mysqladmin ping --password=mysqlrootpassword
      interval: 10s
      timeout: 2s
      retries: 10

  express:
    container_name: express
    build: .
    tty: true
    ports:
      - '5000:5000'
    environment:
      LOG_LEVEL: debug
      DB_HOST: mysql
      DB_DATABASE: crm
      DB_USERNAME: mysqluser
      DB_PASSWORD: mysqlpassword
      DEBUG: 'sequelize:*'
    volumes:
      - ./:/app
    command: sh -c 'npm run dev'
    depends_on:
      mysql:
        condition: service_healthy
